LOC 7409
BetaMasaheft/Places pull request #106
Opened 2024-01-09 10:58 UTC by DenisNosnitsin1970

New place, Taqot.

2024-01-09 11:01 UTC, thea-m requested changes

2024-01-09 11:01 UTC, thea-m commented on new/LOC7409Taqot.xml
> +                <language ident="ti">Tigrinya</language>
here ti and below in the actual name gez (also in the other file)

2024-01-10 11:54 UTC, eu-genia requested changes

2024-01-10 11:54 UTC, eu-genia commented on new/LOC7409Taqot.xml
> +                    <placeName xml:id="n1" xml:lang="gez">ጣቖት፡</placeName>
ti?

2024-01-10 11:54 UTC, eu-genia commented on new/LOC7411HaddesHeywat.xml
> +                    <placeName xml:id="n1" xml:lang="gez">ሓድሽ፡ ህይወት፡</placeName>
ti?

2024-01-10 11:54 UTC, eu-genia commented on new/LOC7409Taqot.xml
> +            </listPlace><!---->
add at least Tigray as region and Ethiopia as country

2024-01-10 11:54 UTC, eu-genia commented on new/LOC7411HaddesHeywat.xml
> +                    <placeName xml:id="n1" xml:lang="gez">ሓድሽ፡ ህይወት፡</placeName>
add at least Tigray as region and Ethiopia as country

2024-01-11 12:09 UTC, eu-genia approved these changes

2024-01-11 12:10 UTC, merged