Create LOC7441Arato.xml
BetaMasaheft/Places pull request #113
Opened 2024-03-22 22:42 UTC by DenisNosnitsin1970

Locality for the church Arato, Abb. 72

2024-03-23 07:41 UTC, CarstenHoffmannMarburg commented
It would be nice to find a reference to the exact location of Arato, if it is clear. My guess is that it should be Arato, east of Mekele.

2024-03-23 07:43 UTC, CarstenHoffmannMarburg approved these changes

2024-03-25 08:40 UTC, thea-m requested changes

2024-03-25 08:40 UTC, thea-m commented on new/LOC7441Arato.xml
> +                <title>ʿArāto</title>
ʿĀ, also below

2024-03-26 13:39 UTC, merged