LOC7454 55
BetaMasaheft/Places pull request #123
Opened 2024-09-10 14:35 UTC by DenisNosnitsin1970

Locations for Dabra Hallelo Enda Abuna Samuel

2024-09-11 06:30 UTC, CarstenHoffmannMarburg requested changes

2024-09-11 06:30 UTC, CarstenHoffmannMarburg commented on new/LOC7454WaddiAmbaray.xml
> +         <placeName corresp="#n1" xml:lang="en">Māy Waddi ʾAmbarāy</placeName>
Māy Waddi ʾĀmbarāy (?)

2024-09-11 06:30 UTC, CarstenHoffmannMarburg commented on 1001-2000/LOC1121AddiAr.xml
> +               <note>The name change from ʿAddi ʾArbaʿǝta to Rāmā ʿAddi ʾArbaʿǝta in 2000s.</note>
ʿAddi ʾArbāʿǝta (mark ā)

2024-09-11 06:30 UTC, CarstenHoffmannMarburg commented on 1001-2000/LOC1121AddiAr.xml
> +               <placeName corresp="#n1" xml:lang="en">ʿAddi ʾArbaʿǝta</placeName>
ʿAddi ʾArbāʿǝta (mark ā)

2024-09-11 06:30 UTC, CarstenHoffmannMarburg commented on 1001-2000/LOC1121AddiAr.xml
> +            <title>ʿAddi ʾArbaʿǝta</title>
ʿAddi ʾArbāʿǝta (mark ā)

2024-09-11 19:57 UTC, DenisNosnitsin1970 commented on 1001-2000/LOC1121AddiAr.xml
> +               <note>The name change from ʿAddi ʾArbaʿǝta to Rāmā ʿAddi ʾArbaʿǝta in 2000s.</note>
ok

2024-09-12 08:02 UTC, CarstenHoffmannMarburg approved these changes

2024-09-12 08:03 UTC, nafisa-valieva approved these changes

2024-09-12 08:03 UTC, eu-genia approved these changes

2024-09-12 09:13 UTC, merged